spring.application.name=DtePedido
server.port=8084

# Configuración H2
spring.datasource.url=jdbc:h2:mem:detallepedidodb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Desactivar Liquibase si no lo usas aún
spring.liquibase.enabled=false